### ISSUE TITLE
Ability to hide analysis popup box

### ISSUE THREAD

**Issue by Vorror** [andrepdo/findbugs-idea#100]
I would like some way to hide the analysis popup window. I'm not referring to the tool window which can be turned off in preferences, but the green popup box that appears when FindBugs completes its analysis.

**Comment by retomerz** [comment]
Will be introduced in 0.9.997

![notification](https://cloud.githubusercontent.com/assets/9657405/8733555/9f56fa3e-2c04-11e5-999b-69a102627d7c.png)

![settings](https://cloud.githubusercontent.com/assets/9657405/8733571/a9e8cd1a-2c04-11e5-937e-9dc71fb2504d.png)

**Comment by retomerz** [comment]
Fixed in version 0.9.997
