### ISSUE TITLE
Add a "debounce" mechanism

### ISSUE THREAD

**Issue by Vorror** [andrepdo/findbugs-idea#101]
Needs to have some sort of ["debounce"](http://davidwalsh.name/javascript-debounce-function) mechanism. Using a combination of auto-compile(intellij setting) and auto analyze(find bugs idea setting) It's possible for findbugs idea to fire many times a second while writing code. This crushes intellij performance.

Findbugs idea needs to have a timer(maybe configurable?) that only fires once every 30/60 seconds after it detects an automake event.

**Comment by retomerz** [comment]
Will be introduced in 0.9.997:
Auto-analyze is delayed by 30 seconds (default).
Default can be changed through property "idea.findbugs.autoanalyze.delaymillis"
in \IDEAHOME\bin\idea.properties

**Comment by retomerz** [comment]
Fixed in version 0.9.997
