### ISSUE TITLE
Creation of customPlugins directory fails when IntelliJ installed as root

### ISSUE THREAD

**Issue by baron1405** [andrepdo/findbugs-idea#102]
I package up IntelliJ, with the Findbugs-IDEA plugin added, as an RPM for distribution and installation on developer machines. Even though this results in IntelliJ being installed as the root user, typically everything works fine because all user or project specific data is written to the user's home directory(e.g. ~/.IntelliJIdea14). Unfortunately, Findbugs-IDEA attempts to create a directory called customPlugins at runtime as a subdirectory of the Findbugs-IDEA installation directory. Since this directory is owned by root, the creation of the directory fails because IntelliJ is not being run as root. Please create this directory in the IntelliJ user-specific data directory (e.g. ~/.IntelliJIdea14). This will allow me to include the FindBugs-IDEA plugin with my pre-provisioned packaging of IntelliJ.

**Comment by retomerz** [comment]
Next release 0.9.997 will contain a fallback

**Comment by retomerz** [comment]
Fixed in version 0.9.997
