### ISSUE TITLE
New version of Find Security Bugs

### ISSUE THREAD

**Issue by h3xstream** [andrepdo/findbugs-idea#107]
I have release a new version of Find Security Bugs. 

[Released Jar](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.h3xstream.findsecbugs%22%20a%3A%22findsecbugs-plugin%22) (Direct [jar](http://search.maven.org/remotecontent?filepath=com/h3xstream/findsecbugs/findsecbugs-plugin/1.4.3/findsecbugs-plugin-1.4.3.jar) download)

[Release notes](https://github.com/h3xstream/find-sec-bugs/releases/tag/version-1.4.3)

Note : 1.4.2 was a silent release. There were major refactoring in that version that could have made it unstable.

**Comment by retomerz** [comment]
Release v0.9.998 is bundled with findsecbugs-plugin-1.4.4, which is the latest release of findsecbugs.
