### ISSUE TITLE
Selectable 'minimum RANK to report"

### ISSUE THREAD

**Issue by robinmb** [andrepdo/findbugs-idea#108]
Thanks for creating this plugin!
Please add to the GUI the ability to select the 'minimum rank to report', similar to the way we can select the 'minimum priority/confidence to report'.

The eclipse findbugs plugin has that feature.

Thanks in advance for your consideration of this request.

**Comment by retomerz** [comment]
v0.9.998 is released which allows to configure "Minimum rank".
