### ISSUE TITLE
Methods annotated @CheckForNull and @Nonnull are not being reported correctly

### ISSUE THREAD

**Issue by bgourlie** [andrepdo/findbugs-idea#109]
Consider the following code.  Running findbugs-idea reports 0 errors:

    package com.company;

    import javax.annotation.CheckForNull;

    public class Main {

        public static void main(String[] args) {
            foo(null);
        }

        public static void foo(@CheckForNull String bar) {
            int len = bar.length(); // NullReferenceException
            System.out.println("Len is " + len);
        }
    }

The result of running this is:
 
    FindBugs-IDEA: Analysis Finished Found 0 bugs in 1 class more... using FindBugs-IDEA 0.9.997 with Findbugs version 3.0.1

**Comment by retomerz** [comment]
This is a FindBugs related feature/problem, and not FindBugs-IDEA.
Please report FindBugs issue here: https://github.com/findbugsproject/findbugs/issues
