### ISSUE TITLE
Test sources are not being analyzed 

### ISSUE THREAD

**Issue by avarabyeu** [andrepdo/findbugs-idea#112]
Maven project, Include test sources checkbox is set to TRUE. After analyze run i see that no classes from 'test' has been analyzed. Idea version: 15.0 (143.381), FindBugs-IDEA version: 0.9.997

**Comment by npetzall** [comment]
Same for Idea 14.0

Information regarding 0 classes found says compiled sources are in same directory as the source which is incorrect.

**Comment by dpinol** [comment]
Same with Idea 16 and FindBugs-IDEA version: 0.9.998.
There's no way to enable findbugs for tests

**Comment by retomerz** [comment]
Fixed in v0.9.999. Please update the plugin.
Thank you for taking the time to submit the issue!
