### ISSUE TITLE
can't configuration in IntelliJ IDEA 2016.1

### ISSUE THREAD

**Issue by myoss** [andrepdo/findbugs-idea#118]
menu: Settings -> Other Settings, not found findbugs-idea

**Comment by myoss** [comment]
![qq 20160330151951](https://cloud.githubusercontent.com/assets/6986459/14144427/3cb76830-f6c2-11e5-9c4c-c1b45c9f3c7f.png)

**Comment by andrepdo** [comment]
> Some deprecated methods were removed from IDEA 16,
> so settings for your plugin are not loaded anymore.
> http://youtrack.jetbrains.com/issue/IDEA-150516
> 
> we should use recommended extension points instead!
> http://sites.google.com/site/malenkov/java/150403
>

**Comment by myoss** [comment]
when release? @andrepdo @retomerz

**Comment by retomerz** [comment]
It is still under development (brach 'modernize': https://github.com/andrepdo/findbugs-idea/tree/modernize).
As a workaround, it is possible to open the settings from to FindBugs Toolwindo, see:
![settings](https://cloud.githubusercontent.com/assets/9657405/15325686/7c760b3a-1c4b-11e6-9e50-1b860c884275.png)

**Comment by myoss** [comment]
it's ok, thanks.

**Comment by retomerz** [comment]
Fixed in v0.9.998.
