### ISSUE TITLE
Report/Minimum rank is ignored

### ISSUE THREAD

**Issue by janxbar** [andrepdo/findbugs-idea#146]
Hi,

thank you for your plugin. I installed version 1.0.0 and it seems that the Report / Minimum rank is ignored, the list of found problems lists all found problems. Say I set minimum rank to "1 - Scariest" but I also see bugs with rank 19. I can verify that with exported bug collection, the GUI does not show rank. This makes the plugin unusable for me.

Kind regards, Jan

**Comment by janxbar** [comment]
Since nobody investigated this problem, I did and found that you should add call to 		`reporter.setRankThreshold(settings.minRank)` in your FindBugsStarter.java.

Kind regards, Jan

**Comment by retomerz** [comment]
@janxbar Thanks for report this issue. This is fixed with version 1.0.1 (rev 4e9f1738a3c2b47d5fa0d106b8548690c82ed00b).
Please update the plugin.
