### ISSUE TITLE
Android Studio java.lang.NullPointerException

### ISSUE THREAD

**Issue by XandrMaster** [andrepdo/findbugs-idea#165]
Hello ! I have a problem in Android Studio.
findbugs version 0.9.999 - 1.0.0 - Issue
findbugs version 0.9.998 < - Correct work
Android Studio version 2.1.3
gradle version 2.1.13
com.android.tools.build:gradle:2.1.2
Exception and screen atached.
Why findbugs started gradle builds ???
[Screen](http://my.jetscreenshot.com/21448/20160820-sfvv-480kb.jpg)
`Error:Gradle: 08:50:09.048 [ERROR] [org.gradle.BuildExceptionReporter] 
08:50:09.050 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
08:50:09.050 [ERROR] [org.gradle.BuildExceptionReporter] 
08:50:09.050 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
08:50:09.050 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':crashlytics:compileReleaseJavaWithJavac'.
08:50:09.051 [ERROR] [org.gradle.BuildExceptionReporter] > java.lang.NullPointerException (no error message)
08:50:09.051 [ERROR] [org.gradle.BuildExceptionReporter] 
08:50:09.051 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
08:50:09.052 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':crashlytics:compileReleaseJavaWithJavac'.
08:50:09.052 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
08:50:09.052 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
08:50:09.052 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
08:50:09.053 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:68)
08:50:09.053 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
08:50:09.053 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
08:50:09.053 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
08:50:09.053 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
08:50:09.053 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
08:50:09.053 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
08:50:09.053 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
08:50:09.054 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
08:50:09.054 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
08:50:09.054 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
08:50:09.054 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
08:50:09.054 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.NullPointerException
08:50:09.054 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.incremental.jar.JarSnapshot.getHashes(JarSnapshot.java:82)
08:50:09.054 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.incremental.jar.JarSnapshot.affectedSince(JarSnapshot.java:54)
08:50:09.054 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.incremental.jar.JarSnapshot.getAffectedClassesSince(JarSnapshot.java:47)
08:50:09.055 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.incremental.jar.JarChangeDependentsFinder.getActualDependents(JarChangeDependentsFinder.java:65)
08:50:09.055 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.incremental.jar.JarChangeProcessor.processChange(JarChangeProcessor.java:39)
08:50:09.055 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.incremental.RecompilationSpecProvider$InputChangeAction.execute(RecompilationSpecProvider.java:77)
08:50:09.055 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.incremental.RecompilationSpecProvider$InputChangeAction.execute(RecompilationSpecProvider.java:57)
08:50:09.055 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.changedetection.changes.ChangesOnlyIncrementalTaskInputs.doOutOfDate(ChangesOnlyIncrementalTaskInputs.java:48)
08:50:09.055 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.changedetection.changes.StatefulIncrementalTaskInputs.outOfDate(StatefulIncrementalTaskInputs.java:46)
08:50:09.055 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.changedetection.changes.ChangesOnlyIncrementalTaskInputs.outOfDate(ChangesOnlyIncrementalTaskInputs.java:28)
08:50:09.055 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.incremental.RecompilationSpecProvider.provideRecompilationSpec(RecompilationSpecProvider.java:48)
08:50:09.056 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.incremental.SelectiveCompiler.execute(SelectiveCompiler.java:54)
08:50:09.056 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.incremental.SelectiveCompiler.execute(SelectiveCompiler.java:31)
08:50:09.056 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilationFinalizer.execute(IncrementalCompilationFinalizer.java:39)
08:50:09.056 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilationFinalizer.execute(IncrementalCompilationFinalizer.java:24)
08:50:09.056 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:163)
08:50:09.056 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:127)
08:50:09.056 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:49)
08:50:09.056 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
08:50:09.057 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
08:50:09.057 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
08:50:09.057 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
08:50:09.057 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
08:50:09.057 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
08:50:09.057 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
08:50:09.057 [ERROR] [org.gradle.BuildExceptionReporter] 	... 14 more
08:50:09.058 [ERROR] [org.gradle.BuildExceptionReporter] 
08:50:09.540 [ERROR] [org.gradle.api.Project] == BUILD FAILED ==
`

**Comment by retomerz** [comment]
Hello,

> Why findbugs started gradle builds ???

The FindBugs-IDEA plugin try to execute the compile task before it starts the FindBugs analysis task **by default**.
FindBugs is a bytecode analysis tool, not source code based. So up-to-date class files are needed..

You can disable that feature in General Settings **"Compile affected files before analyze"**
![compile](https://cloud.githubusercontent.com/assets/9657405/17831190/8ea4f08c-66e2-11e6-921c-d05671bcc435.png)



It looks like that you project does not compile when you have started the FindBugs analysis.
It would be interesting if you project compiles fine when you compile it by yourself ?
In the past, we have already noticed that the standard compile API does not work as expected in case of Gradle/Android project: 
https://intellij-support.jetbrains.com/hc/en-us/community/posts/207521525-CompilerManager-make-does-not-all-tasks-in-case-of-a-Android-module-project

**Comment by XandrMaster** [comment]
Thanks guys for quick response. Just one simple flag :+1: . Everything ok. Thanks.
