### ISSUE TITLE
Mac OS: Detail Vertical TabbedPane broken

### ISSUE THREAD

**Issue by GoogleCodeExporter** [andrepdo/findbugs-idea#74]
```
Mac OS: Detail Vertical TabbedPane broken.

tab of bug details is to low. only cosmetic issue


```

Original issue reported on code.google.com by `andre.pf...@gmail.com` on 9 Jul 2014 at 3:16

**Comment by retomerz** [comment]
Tab is now painted correctly.
Tabs have still center-align on OS X. This can only be changed with an custom TabUI.
But I think this is OK, fighting against native look and feel experience is worthless.

Before
![before](https://cloud.githubusercontent.com/assets/9657405/10003344/32eb738e-60ac-11e5-9067-3a654cbc5b69.png)

After
![after](https://cloud.githubusercontent.com/assets/9657405/10003349/394363c2-60ac-11e5-8d75-4f6a86c0fb83.png)
