### ISSUE TITLE
Broken Layout: IDEA 14.1.x + FindBugs-IDEA + Win8.1 HiDPI 

### ISSUE THREAD

**Issue by paxbit** [andrepdo/findbugs-idea#97]
Hi,

IntelliJ introduced HiDPI support with 14.1, which is still not perfect in many places and which seems to break some plugins' layout - at least on Win8.1. One of them being FindBugs-IDEA. The situation improves naturally and progressively when I step down the OS' display scaling factor from 200% down to 100%, the default for probably all displays until a year or two ago. Of course everything is tiny at 100% on a 14 inch 3200x1800 screen which I'm sitting in front of, unusable tiny.

I attached a screen shot of how the plugin looks at 200% OS scaling. There are already some tickets open at Jetbrains' IDEA tracker and I'm not quite sure if this issue is something fixable within the FB plugin. Can you please confirm if it is. And if so can you fix it in the near future. It's part of our workflow and I like to know if we can use it again soon or if we need to find another solution.

Thanks a lot, cheers,
paxbit

![image](https://cloud.githubusercontent.com/assets/11138536/7337100/2bef6d10-ec1c-11e4-81b0-160a5e7a3b5a.png)

**Comment by retomerz** [comment]
I have done some minor improvements (changes will be included in version 0.9.997)
but to make it perfect we need "high" res icons. IDEA use this notation:

AIcon.png: (non-HiDPI, default size: 16x16)
AIcon@2x.png (HiDPI, default size: 32x32)

And optional darcula theme:

AIcon_dark.png
AIcon@2x_dark.png

**Comment by retomerz** [comment]
Fixed in version 0.9.997
